# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('post_code', models.CharField(max_length=10)),
                ('email', models.EmailField(default=b'', max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=50)),
                ('first_attended', models.DateField(default=b'2014-09-28 15:00')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
