# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True, unique=True)),
            ],
            options={
                'ordering': ['status'],
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200, null=True, unique=True)),
            ],
            options={
                'ordering': ['gender'],
                'verbose_name_plural': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name=b'Mobile number')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name=b'Email Address')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('first_attended', models.DateField(blank=True, null=True)),
                ('last_visited', models.DateField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, max_length=2000)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('academic_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_institution', to='member.AcademicInstitution')),
                ('attendance_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_status', to='member.Attendance')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sex', to='member.Gender')),
                ('shepherd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
