# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_attended',
            field=models.DateField(default=b'2014-09-28'),
        ),
    ]
