# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161113_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='member',
            name='attendance_status',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='extra_info',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_attended',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
