# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20161114_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='attendance_status',
            new_name='category',
        ),
    ]
