# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-31 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20180122_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'Mobile number'),
        ),
    ]
